import { mkdir, readdir, readFile, rm, writeFile } from 'fs/promises'
import matter from 'gray-matter'
import { resolve } from 'path'
import { minify } from '../skill-minifier.js'
import type { HookMeta, SkillMeta } from '../types.js'

export const DEFAULT_COPILOT_MIRROR_ROOT = '.github/harness'

/**
 * Compact mirror for GitHub Copilot: minified skills and hooks under
 * `.github/harness/` (no Agent Skills layout — Copilot reads paths from
 * copilot-instructions.md).
 */
export async function mirrorHarnessForCopilot(opts: {
  projectRoot: string
  mirrorRootRel: string
  skills: SkillMeta[]
  hooks: HookMeta[]
  dryRun: boolean
}): Promise<string[]> {
  const { projectRoot, dryRun, mirrorRootRel } = opts
  const harness = resolve(projectRoot, '.harness')
  const mirrorBase = resolve(projectRoot, mirrorRootRel.trim().replace(/\/+$/, ''))
  const outFiles: string[] = []

  const record = async (dest: string, content: string) => {
    outFiles.push(dest)
    if (!dryRun) {
      await mkdir(resolve(dest, '..'), { recursive: true })
      await writeFile(dest, content, 'utf-8')
    }
  }

  if (!dryRun) {
    await rm(mirrorBase, { recursive: true, force: true })
  }

  // Skills: one flat file per domain (minified)
  const skillsDir = resolve(harness, 'skills')
  let skillDirs: string[] = []
  try {
    const entries = await readdir(skillsDir, { withFileTypes: true })
    skillDirs = entries
      .filter(e => e.isDirectory() && !e.name.startsWith('_'))
      .map(e => e.name)
  } catch {
    /* missing */
  }

  for (const domain of skillDirs) {
    const skillMd = resolve(skillsDir, domain, 'SKILL.md')
    const minMd = resolve(skillsDir, domain, 'SKILL.min.md')
    let raw = await readFile(minMd, 'utf-8').catch(() => null)
    if (!raw) raw = await readFile(skillMd, 'utf-8').catch(() => null)
    if (!raw) continue

    const { content } = matter(raw)
    const compact = minify(content)
    const dest = resolve(mirrorBase, 'skills', `${domain}.md`)
    const wrapped = `# Skill: ${domain}\n\n> Compact mirror — source: \`.harness/skills/${domain}/SKILL.md\`\n\n${compact}`
    await record(dest, wrapped)
  }

  // Hooks: one file per hook (minified body)
  for (const hook of opts.hooks) {
    const raw = await readFile(resolve(harness, 'hooks', hook.file), 'utf-8').catch(() => null)
    if (!raw) continue
    const { content } = matter(raw)
    const compact = minify(content)
    const dest = resolve(mirrorBase, 'hooks', `${hook.name}.md`)
    const wrapped = `# Hook: ${hook.name}\n\n> Compact mirror — source: \`.harness/hooks/${hook.file}\`\n\n${compact}`
    await record(dest, wrapped)
  }

  const readme = resolve(mirrorBase, 'README.md')
  await record(
    readme,
    [
      '# Harness mirror for GitHub Copilot',
      '',
      'Generated by `harness sync`. Do not edit — change `.harness/` and re-sync.',
      '',
      '- `skills/` — minified domain skills',
      '- `hooks/` — minified behavioral hooks',
      '',
      'Referenced from `.github/copilot-instructions.md`.',
      '',
    ].join('\n'),
  )

  return outFiles
}

export function buildCopilotSkillsIndex(
  mirrorRootRel: string,
  skills: SkillMeta[],
): string {
  if (!skills.length) return ''
  const lines = [
    '## Skills (on demand)',
    '',
    'When editing files in a domain, read the matching skill:',
    '',
  ]
  for (const s of skills) {
    const globs = s.globs.length ? ` — \`${s.globs.join('`, `')}\`` : ''
    lines.push(`- **${s.name}** (${s.domain})${globs} → \`${mirrorRootRel}/skills/${s.name}.md\``)
  }
  return lines.join('\n')
}

export function buildCopilotHooksIndex(mirrorRootRel: string, hooks: HookMeta[]): string {
  if (!hooks.length) return ''
  const lines = [
    '## Hooks',
    '',
    'Before starting work, follow `pre-task`. On failures, follow `on-error`.',
    '',
  ]
  for (const h of hooks) {
    const block = h.blocks ? ' (blocking)' : ''
    lines.push(`- **${h.name}**${block}: \`${mirrorRootRel}/hooks/${h.name}.md\``)
  }
  return lines.join('\n')
}
