import { mkdir, writeFile } from 'fs/promises'
import { resolve } from 'path'

/** Curated MCP servers — copy entries into `.cursor/mcp.json` as needed. */
export const RECOMMENDED_MCP_SERVERS = {
  context7: {
    description: 'Up-to-date library and framework documentation',
    url: 'https://mcp.context7.com/mcp',
    note: 'Requires CONTEXT7_API_KEY in env or Cursor MCP settings',
  },
  github: {
    description: 'Issues, pull requests, and repository context',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-github'],
    env: { GITHUB_PERSONAL_ACCESS_TOKEN: '<your-github-pat>' },
  },
  filesystem: {
    description: 'Read/write project files outside default agent scope',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-filesystem', '<absolute-project-root>'],
  },
} as const

export interface McpRecommendedResult {
  jsonPath: string
  docPath: string
}

export async function generateMcpRecommended(opts: {
  projectRoot: string
  /** Relative path for the JSON template (default `.cursor/mcp.recommended.json`). */
  jsonRel?: string
  /** Relative path for the markdown guide (default `.cursor/MCP-RECOMMENDED.md`). */
  docRel?: string
  dryRun: boolean
}): Promise<McpRecommendedResult> {
  const jsonRel = opts.jsonRel ?? '.cursor/mcp.recommended.json'
  const docRel = opts.docRel ?? '.cursor/MCP-RECOMMENDED.md'
  const jsonPath = resolve(opts.projectRoot, jsonRel)
  const docPath = resolve(opts.projectRoot, docRel)

  const mcpJson = {
    _comment:
      'Template generated by harness sync. Copy servers into .cursor/mcp.json — harness never overwrites your live MCP config.',
    mcpServers: {
      context7: { url: RECOMMENDED_MCP_SERVERS.context7.url },
      github: {
        command: RECOMMENDED_MCP_SERVERS.github.command,
        args: RECOMMENDED_MCP_SERVERS.github.args,
        env: RECOMMENDED_MCP_SERVERS.github.env,
      },
      filesystem: {
        command: RECOMMENDED_MCP_SERVERS.filesystem.command,
        args: [
          RECOMMENDED_MCP_SERVERS.filesystem.args[0],
          RECOMMENDED_MCP_SERVERS.filesystem.args[1],
          RECOMMENDED_MCP_SERVERS.filesystem.args[2],
        ],
      },
    },
  }

  const doc = buildMcpDoc(jsonRel)

  if (!opts.dryRun) {
    await mkdir(resolve(jsonPath, '..'), { recursive: true })
    await writeFile(jsonPath, JSON.stringify(mcpJson, null, 2) + '\n', 'utf-8')
    await writeFile(docPath, doc, 'utf-8')
  }

  return { jsonPath, docPath }
}

function buildMcpDoc(jsonRel: string): string {
  const lines = [
    '# Recommended MCP servers (Harness)',
    '',
    '> Generated by `harness sync`. Edit `.harness/` and re-sync; this file is safe to read but will be regenerated.',
    '',
    'Cursor reads MCP configuration from **`.cursor/mcp.json`** (not committed by harness).',
    `Use **\`${jsonRel}\`** as a starting template.`,
    '',
    '## Servers',
    '',
  ]

  for (const [id, server] of Object.entries(RECOMMENDED_MCP_SERVERS)) {
    lines.push(`### \`${id}\``)
    lines.push('')
    lines.push(server.description)
    lines.push('')
    if ('url' in server && server.url) {
      lines.push(`- URL: \`${server.url}\``)
    }
    if ('command' in server && server.command) {
      lines.push(`- Command: \`${server.command} ${server.args.join(' ')}\``)
    }
    if ('env' in server && server.env) {
      lines.push(`- Env: ${Object.keys(server.env).join(', ')}`)
    }
    if ('note' in server && server.note) {
      lines.push(`- Note: ${server.note}`)
    }
    lines.push('')
  }

  lines.push('## Setup')
  lines.push('')
  lines.push('1. Copy the servers you need from `mcp.recommended.json` into `.cursor/mcp.json`.')
  lines.push('2. Replace placeholders (`<your-github-pat>`, project root path).')
  lines.push('3. Restart Cursor or reload MCP from settings.')
  lines.push('')
  lines.push('Harness hooks `on-error` / `pre-task` apply regardless of MCP; MCP extends what tools the agent can call.')
  lines.push('')

  return lines.join('\n')
}
